const data = {
  products: [
    {
      _id: "1",
      title: "Cat Chicken Food",
      category: "pet food",
      image: "/images/p1.png",
      price: "110",
      brand: "Food Elite",
      countInStock: "10",
      quantity: 0,
      weight: "15kg",
    },
    {
      _id: "2",
      title: "Cat Salmon Food",
      category: "pet food",
      image: "/images/p2.png",
      price: "110",
      brand: "Food Elite",
      countInStock: "10",
      quantity: 0,
      weight: "15kg",
    },
    {
      _id: "3",
      title: "Dog Chicken Food",
      category: "pet food",
      image: "/images/p3.png",
      price: "110",
      brand: "Food Elite",
      countInStock: "10",
      quantity: 0,
      weight: "15kg",
    },
    {
      _id: "4",
      title: "Dog Salmon Food",
      category: "pet food",
      image: "/images/p4.png",
      price: "110",
      brand: "Food Elite",
      countInStock: "10",
      quantity: 0,
      weight: "15kg",
    },
    {
      _id: "5",
      title: "Dog Beef Meal",
      category: "pet food",
      image: "/images/p5.png",
      price: "110",
      brand: "Food Elite",
      countInStock: "0",
      quantity: 0,
      weight: "15kg",
    },
    {
      _id: "6",
      title: "Puppy Food",
      category: "pet food",
      image: "/images/p6.png",
      price: "45",
      brand: "Food Elite",
      countInStock: "10",
      quantity: 0,
      weight: "3kg",
    },
  ],
};

export default data;
