const data = {
  products: [
    {
      _id: "1",
      title: "Cat Chicken Food",
      category: "pet food",
      image: "/images/p1.png",
      price: "110",
      brand: "Food Elite",
      countInStock: "10",
      quantity: 0,
      weight: "15kg",
    },
    {
      _id: "2",
      title: "Cat Salmon Food",
      category: "pet food",
      image: "/images/p2.png",
      price: "110",
      brand: "Food Elite",
      countInStock: "10",
      quantity: 0,
      weight: "15kg",
    },
    {
      _id: "3",
      title: "Dog Chicken Food",
      category: "pet food",
      image: "/images/p3.png",
      price: "110",
      brand: "Food Elite",
      countInStock: "10",
      quantity: 0,
      weight: "15kg",
    },
    {
      _id: "4",
      title: "Dog Salmon Food",
      category: "pet food",
      image: "/images/p4.png",
      price: "110",
      brand: "Food Elite",
      countInStock: "10",
      quantity: 0,
      weight: "15kg",
    },
    {
      _id: "5",
      title: "Dog Beef Meal",
      category: "pet food",
      image: "/images/p5.png",
      price: "110",
      brand: "Food Elite",
      countInStock: "0",
      quantity: 0,
      weight: "15kg",
    },
    {
      _id: "6",
      title: "Puppy Food",
      category: "pet food",
      image: "/images/p6.png",
      price: "45",
      brand: "Food Elite",
      countInStock: "10",
      quantity: 0,
      weight: "3kg",
    },
    {
      _id: "7",
      title: "Dog Dry Chicken Food",
      category: "pet food",
      image: "/images/p7.JPG",
      price: "65",
      brand: "Pedigree",
      countInStock: "10",
      quantity: 0,
      weight: "12kg",
    },
    {
      _id: "8",
      title: "Pedigree Small Breed Adult Dry Dog Food, Chicken & Steak",
      category: "pet food",
      image: "/images/p8.JPG",
      price: "65",
      brand: "Pedigree",
      countInStock: "10",
      quantity: 0,
      weight: "12kg",
    },
    {
      _id: "9",
      title: "Eukanuba Senior Large Breed Dry Dog Food, 30 lb. bag",
      category: "pet food",
      image: "/images/p9.JPG",
      price: "95",
      brand: "Eukanuba",
      countInStock: "10",
      quantity: 0,
      weight: "9kg",
    },
    {
      _id: "10",
      title: "Eukanuba Adult Medium Breed Dry Dog Food, 30 lb. bag",
      category: "pet food",
      image: "/images/p10.png",
      price: "120",
      brand: "Eukanuba",
      countInStock: "10",
      quantity: 0,
      weight: "12kg",
    },
    {
      _id: "11",
      title:
        "ORIJEN Dry Dog Food, Grain Free, High Protein, Fresh and Raw Animal Ingredients",
      category: "pet food",
      image: "/images/p11.png",
      price: "100",
      brand: "ORIJEN",
      countInStock: "10",
      quantity: 0,
      weight: "14kg",
    },
    {
      _id: "12",
      title: "Royal Canin French Bulldog Adult Breed Specific",
      category: "pet food",
      image: "/images/p12.png",
      price: "180",
      brand: "Royal Canin",
      countInStock: "10",
      quantity: 0,
      weight: "4kg",
    },
    {
      _id: "13",
      title:
        "Royal Canin Great Dane Adult Breed Specific Dry Dog Food, 30 lb. bag",
      category: "pet food",
      image: "/images/p13.png",
      price: "165",
      brand: "Royal Canin",
      countInStock: "10",
      quantity: 0,
      weight: "12kg",
    },
    {
      _id: "14",
      title: "Royal Canin German Shepherd Adult Breed Specific Dry Dog Food",
      category: "pet food",
      image: "/images/p14.png",
      price: "210",
      brand: "Royal Canin",
      countInStock: "10",
      quantity: 0,
      weight: "7kg",
    },
    {
      _id: "15",
      title: "Wagner's 62004 Eastern Regional Wild Bird Food, 20-Pound Bag",
      category: "pet food",
      image: "/images/p15.png",
      price: "45",
      brand: "Wagner's",
      countInStock: "10",
      quantity: 0,
      weight: "2kg",
    },
    {
      _id: "16",
      title: "Lyric 2647416 Chickadee Wild Bird Mix, 20 lb",
      category: "pet food",
      image: "/images/p16.png",
      price: "30",
      brand: "Lyric",
      countInStock: "10",
      quantity: 0,
      weight: "1kg",
    },
    {
      _id: "17",
      title: "Volkman Avian Science Super African Grey Bird Food",
      category: "pet food",
      image: "/images/p17.png",
      price: "85",
      brand: "Volkman",
      countInStock: "10",
      quantity: 0,
      weight: "3kg",
    },
    {
      _id: "18",
      title: "Wild Delight Sizzle N' Heat Bird Food, 5 lb",
      category: "pet food",
      image: "/images/p18.png",
      price: "32",
      brand: "Wild Delight",
      countInStock: "10",
      quantity: 0,
      weight: "600g",
    },
    {
      _id: "19",
      title:
        "Pretty Bird International Bpb79118 20-Pound Daily Select Premium Bird Food, Large",
      category: "pet food",
      image: "/images/p19.JPG",
      price: "41",
      brand: "Pretty Bird",
      countInStock: "10",
      quantity: 0,
      weight: "850g",
    },
    {
      _id: "20",
      title: "Less Mess Wild Bird Food Mix (5 Lbs)",
      category: "pet food",
      image: "/images/p20.JPG",
      price: "58",
      brand: "Less Mess",
      countInStock: "10",
      quantity: 0,
      weight: "1kg",
    },
    {
      _id: "21",
      title: "Wagner's 62046 Backyard Wildlife Food, 8-Pound Bag",
      category: "pet food",
      image: "/images/p21.JPG",
      price: "26",
      brand: "Wagner's",
      countInStock: "10",
      quantity: 0,
      weight: "1.3kg",
    },
    {
      _id: "22",
      title:
        "Pretty Bird International Bpb79118 20-Pound Daily Select Premium Bird Food, Large",
      category: "pet food",
      image: "/images/p22.JPG",
      price: "21",
      brand: "Pretty Bird",
      countInStock: "10",
      quantity: 0,
      weight: "1.5kg",
    },
  ],
};

export default data;
